version: '3.7'

volumes:
  prometheus_data: {}

services:
  app:
    image: recipes-project-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DB_URL=jdbc:postgresql://dbpostgresql:5432/recipes_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - dbpostgresql
#      dbpostgresql:
#        condition: service_healthy
  dbpostgresql:
    image: postgres
    container_name: postgresql-container
    restart: unless-stopped
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recipes_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - app
    restart: unless-stopped
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}